# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#  node: circleci/node@5.0.0

jobs:
  unit_testing:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install dependencies
          command: docker build --target deps . -t mzymta/react-test
      - run:
          name: Run tests
          command: docker run mzymta/react-test npm run test:ci
  build:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build
          command: docker build --target builder . -t mzymta/react-test


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  prebuild:
    jobs:
      - unit_testing
      - build:
          requires:
            - unit_testing


