# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

commands:
  restore_image:
    description: restore docker image from cache
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /tmp/workspace/react-test.tar | true
  save_image:
    description: save docker image to cache
    steps:
      - run:
          name: Save Docker image layer cache
          command: docker save -o react-test.tar react-test
      - persist_to_workspace:
          root: .
          paths:
            - ./react-test.tar

jobs:
  intall_dependencies:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_image
      - run:
          name: Install dependencies
          command: docker build --cache-from=react-test --target deps . -t react-test
      - save_image
  unit_testing:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_image
      - run:
          name: Run tests
          command: docker run react-test npm run test:ci
      - store_test_results:
          path: /test-results/jest/
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_image
      - run:
          name: Build
          command: docker build --cache-from=react-test . -t react-test
      - save_image


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test_build_deploy:
    jobs:
      - aws-elastic-beanstalk/deploy:
          application-name: react-test
          environment-name: Reacttest-env
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
