# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

persist_to_workspace:
  root: ./
  paths:
    - app.tar

commands:
  restore_image:
    description: restore docker image from cache
    steps:
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /app.tar | true
  save_image:
    description: save docker image to cache
    steps:
      - run:
          name: Save Docker image layer cache
          command: docker save -o /app.tar app
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - /app.tar


jobs:
  unit_testing:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - restore_image
      - run:
          name: Install dependencies
          command: docker build --cache-from=app --target deps . -t app
      - run:
          name: LIST THE DIR CONTENT
          command: echo $(ls)
      - save_image
      - run:
          name: Run tests
          command: docker run app npm run test:ci
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - restore_image
      - run:
          name: Build
          command: docker build --cache-from=app --target builder . -t app
      - save_image


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  pipeline:
    jobs:
      - unit_testing
      - build:
          requires:
            - unit_testing


