# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

commands:
  restore_image:
    description: restore docker image from cache
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /tmp/workspace/react-test.tar | true
  save_image:
    description: save docker image to cache
    steps:
      - run:
          name: Save Docker image layer cache
          command: docker save -o react-test.tar react-test
      - persist_to_workspace:
          root: .
          paths:
            - ./react-test.tar

jobs:
  unit_testing:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_image
      - run:
          name: Install dependencies
          command: docker build --cache-from=react-test --target deps . -t react-test
      - run:
          name: LIST THE DIR CONTENT
          command: echo $(ls)
      - save_image
      - run:
          name: Run tests
          command: docker run react-test npm run test:ci
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_image
      - run:
          name: Build
          command: docker build --cache-from=react-test --target builder . -t react-test
      - save_image
  build2:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build
          command: docker build --target builder . -t react-test



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  pipeline:
    jobs:
      - build2


